<?php
include_once './dataRead/ReadDB.php';
include_once './dataRead/ReadJson.php';
include_once './dataRead/ReadXML.php';
include_once './dataRead/ReadAPI.php';
include_once './dataWrite/WriteXML.php';
include_once './dataWrite/WriteJson.php';
include_once './dataWrite/WriteDB.php';


echo "Dane z jsona";
$json = new ReadJson();
$data = $json -> ReadData();
echo "<br/>";
echo "<br/>";
echo "<br/>";
var_dump($data);
echo "<br/>";
echo "<br/>";
echo "Dane z XMLa";
$xml = new ReadXML();
$data2 = $xml -> ReadData();
echo "<br/>";
echo "<br/>";
echo "<br/>";
var_dump($data2);
echo "<br/>";
echo "<br/>";
echo "dane z DB";
$db = new ReadDataDB();
$data3 = $db -> ReadData();
echo "<br/>";
echo "<br/>";
echo "<br/>";
var_dump($data3);
echo "<br/>";
echo "<br/>";
echo "<br/>";
echo "dane z API";
$api = new ReadAPI();
$data4 = $api -> ReadData("IT");
echo "<br/>";
echo "<br/>";
echo "<br/>";
var_dump($data4);