<?php
include_once './dataRead/ReadDB.php';
include_once './dataRead/ReadJson.php';
include_once './dataRead/ReadXML.php';
include_once './dataRead/ReadAPI.php';
include_once './dataWrite/WriteXML.php';
include_once './dataWrite/WriteJson.php';
include_once './dataWrite/WriteDB.php';

echo "dane z DB";
echo "<br>";
$db = new ReadDataDB();
var_dump($db->ReadData());
echo "<br>";
echo "<br>";
echo "<br>";
echo "Dane z JSON";
echo "<br>";
$json = new ReadJson();
$dataJson = $json->ReadData("DataItaly.json");
var_dump($dataJson);
echo "<br>";
echo "<br>";
echo "<br>";
echo "Dane z API";
echo "<br>";
$api = new ReadAPI();
var_dump($api->ReadData("UK"));
echo "<br>";
echo "<br>";
echo "<br>";
echo "Dane z XML";
echo "<br>";
$xml2 = new ReadXML();
var_dump($xml2->ReadData("DataItaly.xml"));
echo "<br>";
echo "<br>";
echo "<br>";
echo "Dane do Json";
echo "<br>";
//$json2 = new WriteJson();
//$json2->write($dataJson[0]);
echo "<br>";
echo "<br>";
echo "<br>";
echo "Dane do XML";
echo "<br>";
//$xml = new WriteXML();
//$xml->write($dataJson[0]);
echo "<br>";
echo "<br>";
echo "<br>";
echo "Dane do DB";
echo "<br>";
//$db2 = new WriteDB();
//$db2->write($dataJson[0]);
